export const CHALLONGE_TOURNAMENTS_LIST_REQUEST = 'APP/CHALLONGE/TOURNAMENTS/LIST_REQUEST';
export const CHALLONGE_TOURNAMENTS_LIST_SUCESS = 'APP/CHALLONGE/TOURNAMENTS/LIST_SUCESS';
export const CHALLONGE_TOURNAMENTS_LIST_ERROR = 'APP/CHALLONGE/TOURNAMENTS/LIST_ERROR';

export const CHALLONGE_MATCHES_LIST_REQUEST = 'APP/CHALLONGE/MATCHES/LIST_REQUEST';
export const CHALLONGE_MATCHES_LIST_SUCESS = 'APP/CHALLONGE/MATCHES/LIST_SUCESS';
export const CHALLONGE_MATCHES_LIST_ERROR = 'APP/CHALLONGE/MATCHES/LIST_ERROR';

export const CHALLONGE_MATCH_SET_SELECTED = 'APP/CHALLONGE/MATCH/SET_SELECTED';

export const loadListTournaments = () => {
    return { type: CHALLONGE_TOURNAMENTS_LIST_REQUEST };
};

export const loadListMatches = (tournamentId) => {
    return { type: CHALLONGE_MATCHES_LIST_REQUEST, tournamentId };
};

export const setChallongeSelectedMatch = (match) => {
    return { type: CHALLONGE_MATCH_SET_SELECTED, match };
};
